-- 코드를 작성해주세요
SELECT
    E.ID,
    IFNULL(X.CNT, 0) AS CHILD_COUNT
FROM
    ECOLI_DATA AS E
LEFT JOIN
    (SELECT PARENT_ID AS ID, COUNT(*) AS CNT FROM ECOLI_DATA WHERE PARENT_ID is not null GROUP BY PARENT_ID) AS X
ON
    E.ID = X.ID
