-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE TLNO is not null AND DATE_OF_BIRTH LIKE '____-03-__' AND GENDER = 'W'
ORDER BY MEMBER_ID;